# Rutas
dev_data_dir: "../data/data/"
eval_data_dir: "../data/data" # El query selecciona la carpeta de test
dev_features_dir: "../data/Features/melspec_311_128"
eval_features_dir: "../data/Features/melspec_311_128"
model_dir: "./model_output/CNN/recon1kl1" # _ significa . decimal
results_dir: "./results/CNN/recon1kl1"
# Audio
feature:
  n_mels: 128
  n_fft: 1024
  hop_length: 512 # Numero de muestras que se saltan entre frames del espectrograma

# Aleatoriedad
seed: 42

# Modelo
model:
  latent_dim: 32

# Entrenamiento
train:
  batch_size: 32
  epochs: 30
  learning_rate: 0.001
  # validation_split: 0.1
  # Pesos de Loss (Requisito clave)
  w_recon: 1.0
  w_kl: 1.0
