# Rutas
dev_data_dir: "../data/data/"
eval_data_dir: "../data/data" # El query selecciona la carpeta de test
dev_features_dir: "../data/Features/melspec_313_128"
eval_features_dir: "../data/Features/melspec_313_128"
model_dir: "./model_output/recon1kl0_15" # _ significa . decimal
results_dir: "./results/ae"
# Audio
feature:
  n_mels: 128
  n_fft: 1024
  hop_length: 512 # Numero de muestras que se saltan entre frames del espectrograma
  frames: 5 # Numero de frames del espectrograma por vector
  n_hop_frames: 4 # Numero de frames que se saltan entre vectores

# Aleatoriedad
seed: 42

# Modelo
model:
  latent_dim: 8
  hidden_dims: 128

# Entrenamiento
train:
  batch_size: 32
  epochs: 30
  learning_rate: 0.001
  # validation_split: 0.1
  # Pesos de Loss (Requisito clave)
  w_recon: 1.0
  w_kl: 0.15
